import { CONTAINERS, MODE_OPTIONS, UOM_OPTIONS, WEIGHT_UNIT_OPTIONS } from '@/utils/cbmCalculations';

export const CBM_UI_STRINGS = [
    'Inputs',
    'Mode',
    'Mode: Meter',
    'Mode: Inches',
    'Mode: Cubic Meter (m³)',
    'UOM',
    'Length',
    'Width',
    'Height',
    'Weight',
    'Unit',
    'Qty',
    'HS code',
    'Results',
    'Calculating…',
    'Live calculation unavailable. Showing local estimate.',
    'Volume (Cubic Meter)',
    'Volume (Cubic Feet)',
    'Weight (Kg)',
    'Weight (lb)',
    'Volumetric Weight Sea (Kg)',
    'Volumetric Weight Sea (lb)',
    'Volumetric Weight Air (Kg)',
    'Volumetric Weight Air (lb)',
    '20 Feet Container',
    '40 Feet Container',
    '40 Feet HC Container',
    'Enter length, width, and height to calculate CBM, volumetric weight, and container capacity.',
    'Sea freight volumetric weight uses L × W × H (cm) ÷ 5000. Air freight uses ÷ 6000. Container counts use standard shipping container dimensions.',
    'Sea freight volumetric weight uses L × W × H (inches, converted to cm) ÷ 5000. Air freight uses ÷ 6000. Weight shown in lb.',
    'L cm',
    'W cm',
    'H cm',
    'units',
    'Could not translate. Try again.',
    ...MODE_OPTIONS.map((option) => option.label),
    ...UOM_OPTIONS.map((option) => option.label),
    ...WEIGHT_UNIT_OPTIONS.map((option) => option.label),
    ...Object.values(CONTAINERS).map((container) => container.label),
];
