export const JOB_POST_FLOW_UI_STRINGS = [
    'Which speciality fits your job?',
    'Pick the closest match.',
    'Tell us about your cargo',
    'Container type, HS code, weight and dimensions help providers quote accurately.',
    'Where is the shipment going?',
    'Where is this shipment coming from?',
    'Where should this shipment go?',
    'Select the country first, then the city.',
    'Job title & description',
    'Review the suggested title and description — edit either if you like.',
    'Your email and contact number',
    'We\'ll send quotes here and reach you if a provider needs a quick detail. Already a member? Log in instead.',
    'Contact number',
    'you@example.com',
    'Review and post',
    'Check everything looks right, then post your job.',
    'File attached',
    '0 skill(s) selected',
    'skill(s) selected',
    'LCL packing',
    'Same products',
    'Multiple different products',
    'Add box',
    'Box',
];
