export const JOB_POST_DYNAMIC_FORM_STRINGS = [
    'Postcode',
    'Where is the project located?',
    'Property Type',
    'House',
    'Flat',
    'Bungalow',
    'Commercial',
    'Other',
    'Project Timeline',
    'ASAP',
    'Within 1 month',
    '1-3 months',
    '3-6 months',
    'Flexible',
    'Additional Requirements',
    'Access restrictions, materials preferences, or other notes',
    'Origin Country',
    'Origin City',
    'Destination Country',
    'Destination City',
    'HS Code',
    'Harmonized System code for your goods (e.g. 8471.30)',
    'Gross Weight kg',
    'Approximate total weight in kilograms',
    'Container Type',
    'Full Container',
    'LCL',
    'Full Container (FCL) for a whole container, or LCL for a shared load.',
    'Dimensions CBM',
    'Enter package dimensions to calculate cubic metres (CBM).',
];
