export const JOB_POST_FLOW_UI_STRINGS = [
    'Which speciality fits your job?',
    'Pick the closest match.',
    'Tell us about your cargo',
    'Container type, HS code, weight and dimensions help providers quote accurately.',
    'Where is the shipment going?',
    'Where is this shipment coming from?',
    'Where should this shipment go?',
    'Select the country first, then the city.',
    'Job title & description',
    'Review the suggested title and description — edit either if you like.',
    'Your contact details',
    'We\'ll use this to create your account when you publish — no password needed here. Already a member? Log in instead.',
    'Review and post',
    'Check everything looks right, then post your job.',
    'File attached',
    '0 skill(s) selected',
    'skill(s) selected',
    'LCL packing',
    'Same products',
    'Multiple different products',
    'Add box',
    'Box',
];
